---
name: Github Actions run in GMT
author: Arne Tarara
description: GMT starts a GitHub Actions Runner and executes a pipeline job

services:
  actions-runner:
    type: container
    build:
      context: .

flow:
  - name: Register Runner
    container: actions-runner
    commands:
      - type: console
        command: ./config.sh --url https://github.com/green-coding-solutions --token __GMT_VAR_RUNNER_TOKEN__ --unattended --name eco-ci-runner-M4 --labels eco-ci-runner-M4 --no-default-labels --ephemeral
  - name: Run Job
    container: actions-runner
    commands:
      - type: console
        command: ./run.sh --url https://github.com/green-coding-solutions --token __GMT_VAR_RUNNER_TOKEN__ --unattended --name eco-ci-runner-M4 --labels eco-ci-runner-M4 --no-default-labels --ephemeral
  - name: Remove Runner
    container: actions-runner
    commands:
      - type: console
        command: ./config.sh remove --token __GMT_VAR_RUNNER_TOKEN__